services:
  dev-container-service:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: dev-container
    working_dir: /app
    stdin_open: true    
    tty: true 
    environment:
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}    
      - WATCHPACK_POLLING=${WATCHPACK_POLLING}      
      - FAST_REFRESH=${FAST_REFRESH}           
      - POLLING_INTERVAL=${POLLING_INTERVAL}     
      - WDS_SOCKET_PORT=${WDS_SOCKET_PORT}  
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "8080:5713"
    

volumes:
  node_modules:
